'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
	Imports System.Collections.Generic
Namespace WCF

	Partial Public Class Customer
		Public Sub New()
			Me.Orders = New HashSet(Of Order)()
			Me.CustomerDemographics = New HashSet(Of CustomerDemographic)()
		End Sub

		Private privateCustomerID As String
		Public Property CustomerID() As String
			Get
				Return privateCustomerID
			End Get
			Set(ByVal value As String)
				privateCustomerID = value
			End Set
		End Property
		Private privateCompanyName As String
		Public Property CompanyName() As String
			Get
				Return privateCompanyName
			End Get
			Set(ByVal value As String)
				privateCompanyName = value
			End Set
		End Property
		Private privateContactName As String
		Public Property ContactName() As String
			Get
				Return privateContactName
			End Get
			Set(ByVal value As String)
				privateContactName = value
			End Set
		End Property
		Private privateContactTitle As String
		Public Property ContactTitle() As String
			Get
				Return privateContactTitle
			End Get
			Set(ByVal value As String)
				privateContactTitle = value
			End Set
		End Property
		Private privateAddress As String
		Public Property Address() As String
			Get
				Return privateAddress
			End Get
			Set(ByVal value As String)
				privateAddress = value
			End Set
		End Property
		Private privateCity As String
		Public Property City() As String
			Get
				Return privateCity
			End Get
			Set(ByVal value As String)
				privateCity = value
			End Set
		End Property
		Private privateRegion As String
		Public Property Region() As String
			Get
				Return privateRegion
			End Get
			Set(ByVal value As String)
				privateRegion = value
			End Set
		End Property
		Private privatePostalCode As String
		Public Property PostalCode() As String
			Get
				Return privatePostalCode
			End Get
			Set(ByVal value As String)
				privatePostalCode = value
			End Set
		End Property
		Private privateCountry As String
		Public Property Country() As String
			Get
				Return privateCountry
			End Get
			Set(ByVal value As String)
				privateCountry = value
			End Set
		End Property
		Private privatePhone As String
		Public Property Phone() As String
			Get
				Return privatePhone
			End Get
			Set(ByVal value As String)
				privatePhone = value
			End Set
		End Property
		Private privateFax As String
		Public Property Fax() As String
			Get
				Return privateFax
			End Get
			Set(ByVal value As String)
				privateFax = value
			End Set
		End Property

		Private privateOrders As ICollection(Of Order)
		Public Overridable Property Orders() As ICollection(Of Order)
			Get
				Return privateOrders
			End Get
			Set(ByVal value As ICollection(Of Order))
				privateOrders = value
			End Set
		End Property
		Private privateCustomerDemographics As ICollection(Of CustomerDemographic)
		Public Overridable Property CustomerDemographics() As ICollection(Of CustomerDemographic)
			Get
				Return privateCustomerDemographics
			End Get
			Set(ByVal value As ICollection(Of CustomerDemographic))
				privateCustomerDemographics = value
			End Set
		End Property
	End Class
End Namespace
