'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
	Imports System.Collections.Generic
Namespace WCF

	Partial Public Class CustomerDemographic
		Public Sub New()
			Me.Customers = New HashSet(Of Customer)()
		End Sub

		Private privateCustomerTypeID As String
		Public Property CustomerTypeID() As String
			Get
				Return privateCustomerTypeID
			End Get
			Set(ByVal value As String)
				privateCustomerTypeID = value
			End Set
		End Property
		Private privateCustomerDesc As String
		Public Property CustomerDesc() As String
			Get
				Return privateCustomerDesc
			End Get
			Set(ByVal value As String)
				privateCustomerDesc = value
			End Set
		End Property

		Private privateCustomers As ICollection(Of Customer)
		Public Overridable Property Customers() As ICollection(Of Customer)
			Get
				Return privateCustomers
			End Get
			Set(ByVal value As ICollection(Of Customer))
				privateCustomers = value
			End Set
		End Property
	End Class
End Namespace
