'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
	Imports System.Data.Entity
	Imports System.Data.Entity.Infrastructure
Namespace WCF

	Partial Public Class northwindEntities
		Inherits DbContext
		Public Sub New()
			MyBase.New("name=northwindEntities")
		End Sub

		Protected Overrides Sub OnModelCreating(ByVal modelBuilder As DbModelBuilder)
			Throw New UnintentionalCodeFirstException()
		End Sub

		Private privateCategories As DbSet(Of Category)
		Public Property Categories() As DbSet(Of Category)
			Get
				Return privateCategories
			End Get
			Set(ByVal value As DbSet(Of Category))
				privateCategories = value
			End Set
		End Property
		Private privateContacts As DbSet(Of Contact)
		Public Property Contacts() As DbSet(Of Contact)
			Get
				Return privateContacts
			End Get
			Set(ByVal value As DbSet(Of Contact))
				privateContacts = value
			End Set
		End Property
		Private privateCustomerDemographics As DbSet(Of CustomerDemographic)
		Public Property CustomerDemographics() As DbSet(Of CustomerDemographic)
			Get
				Return privateCustomerDemographics
			End Get
			Set(ByVal value As DbSet(Of CustomerDemographic))
				privateCustomerDemographics = value
			End Set
		End Property
		Private privateCustomers As DbSet(Of Customer)
		Public Property Customers() As DbSet(Of Customer)
			Get
				Return privateCustomers
			End Get
			Set(ByVal value As DbSet(Of Customer))
				privateCustomers = value
			End Set
		End Property
		Private privateEmployees As DbSet(Of Employee)
		Public Property Employees() As DbSet(Of Employee)
			Get
				Return privateEmployees
			End Get
			Set(ByVal value As DbSet(Of Employee))
				privateEmployees = value
			End Set
		End Property
		Private privateOrder_Details As DbSet(Of Order_Detail)
		Public Property Order_Details() As DbSet(Of Order_Detail)
			Get
				Return privateOrder_Details
			End Get
			Set(ByVal value As DbSet(Of Order_Detail))
				privateOrder_Details = value
			End Set
		End Property
		Private privateOrders As DbSet(Of Order)
		Public Property Orders() As DbSet(Of Order)
			Get
				Return privateOrders
			End Get
			Set(ByVal value As DbSet(Of Order))
				privateOrders = value
			End Set
		End Property
		Private privateProducts As DbSet(Of Product)
		Public Property Products() As DbSet(Of Product)
			Get
				Return privateProducts
			End Get
			Set(ByVal value As DbSet(Of Product))
				privateProducts = value
			End Set
		End Property
		Private privateRegions As DbSet(Of Region)
		Public Property Regions() As DbSet(Of Region)
			Get
				Return privateRegions
			End Get
			Set(ByVal value As DbSet(Of Region))
				privateRegions = value
			End Set
		End Property
		Private privateShippers As DbSet(Of Shipper)
		Public Property Shippers() As DbSet(Of Shipper)
			Get
				Return privateShippers
			End Get
			Set(ByVal value As DbSet(Of Shipper))
				privateShippers = value
			End Set
		End Property
		Private privateSuppliers As DbSet(Of Supplier)
		Public Property Suppliers() As DbSet(Of Supplier)
			Get
				Return privateSuppliers
			End Get
			Set(ByVal value As DbSet(Of Supplier))
				privateSuppliers = value
			End Set
		End Property
		Private privatesysdiagrams As DbSet(Of sysdiagram)
		Public Property sysdiagrams() As DbSet(Of sysdiagram)
			Get
				Return privatesysdiagrams
			End Get
			Set(ByVal value As DbSet(Of sysdiagram))
				privatesysdiagrams = value
			End Set
		End Property
		Private privateTerritories As DbSet(Of Territory)
		Public Property Territories() As DbSet(Of Territory)
			Get
				Return privateTerritories
			End Get
			Set(ByVal value As DbSet(Of Territory))
				privateTerritories = value
			End Set
		End Property
	End Class
End Namespace
