'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
	Imports System.Collections.Generic
Namespace WCF

	Partial Public Class Order_Detail
		Private privateOrderID As Integer
		Public Property OrderID() As Integer
			Get
				Return privateOrderID
			End Get
			Set(ByVal value As Integer)
				privateOrderID = value
			End Set
		End Property
		Private privateProductID As Long
		Public Property ProductID() As Long
			Get
				Return privateProductID
			End Get
			Set(ByVal value As Long)
				privateProductID = value
			End Set
		End Property
		Private privateUnitPrice As Decimal
		Public Property UnitPrice() As Decimal
			Get
				Return privateUnitPrice
			End Get
			Set(ByVal value As Decimal)
				privateUnitPrice = value
			End Set
		End Property
		Private privateQuantity As Short
		Public Property Quantity() As Short
			Get
				Return privateQuantity
			End Get
			Set(ByVal value As Short)
				privateQuantity = value
			End Set
		End Property
		Private privateDiscount As Single
		Public Property Discount() As Single
			Get
				Return privateDiscount
			End Get
			Set(ByVal value As Single)
				privateDiscount = value
			End Set
		End Property

		Private privateOrder As Order
		Public Overridable Property Order() As Order
			Get
				Return privateOrder
			End Get
			Set(ByVal value As Order)
				privateOrder = value
			End Set
		End Property
		Private privateProduct As Product
		Public Overridable Property Product() As Product
			Get
				Return privateProduct
			End Get
			Set(ByVal value As Product)
				privateProduct = value
			End Set
		End Property
	End Class
End Namespace
