'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
	Imports System.Collections.Generic
Namespace WCF

	Partial Public Class Product
		Public Sub New()
			Me.Order_Details = New HashSet(Of Order_Detail)()
		End Sub

		Private privateProductID As Long
		Public Property ProductID() As Long
			Get
				Return privateProductID
			End Get
			Set(ByVal value As Long)
				privateProductID = value
			End Set
		End Property
		Private privateProductName As String
		Public Property ProductName() As String
			Get
				Return privateProductName
			End Get
			Set(ByVal value As String)
				privateProductName = value
			End Set
		End Property
		Private privateSupplierID As Nullable(Of Integer)
		Public Property SupplierID() As Nullable(Of Integer)
			Get
				Return privateSupplierID
			End Get
			Set(ByVal value As Nullable(Of Integer))
				privateSupplierID = value
			End Set
		End Property
		Private privateCategoryID As Nullable(Of Integer)
		Public Property CategoryID() As Nullable(Of Integer)
			Get
				Return privateCategoryID
			End Get
			Set(ByVal value As Nullable(Of Integer))
				privateCategoryID = value
			End Set
		End Property
		Private privateQuantityPerUnit As String
		Public Property QuantityPerUnit() As String
			Get
				Return privateQuantityPerUnit
			End Get
			Set(ByVal value As String)
				privateQuantityPerUnit = value
			End Set
		End Property
		Private privateUnitPrice As Nullable(Of Decimal)
		Public Property UnitPrice() As Nullable(Of Decimal)
			Get
				Return privateUnitPrice
			End Get
			Set(ByVal value As Nullable(Of Decimal))
				privateUnitPrice = value
			End Set
		End Property
		Private privateUnitsInStock As Nullable(Of Short)
		Public Property UnitsInStock() As Nullable(Of Short)
			Get
				Return privateUnitsInStock
			End Get
			Set(ByVal value As Nullable(Of Short))
				privateUnitsInStock = value
			End Set
		End Property
		Private privateUnitsOnOrder As Nullable(Of Short)
		Public Property UnitsOnOrder() As Nullable(Of Short)
			Get
				Return privateUnitsOnOrder
			End Get
			Set(ByVal value As Nullable(Of Short))
				privateUnitsOnOrder = value
			End Set
		End Property
		Private privateReorderLevel As Nullable(Of Short)
		Public Property ReorderLevel() As Nullable(Of Short)
			Get
				Return privateReorderLevel
			End Get
			Set(ByVal value As Nullable(Of Short))
				privateReorderLevel = value
			End Set
		End Property
		Private privateDiscontinued As Boolean
		Public Property Discontinued() As Boolean
			Get
				Return privateDiscontinued
			End Get
			Set(ByVal value As Boolean)
				privateDiscontinued = value
			End Set
		End Property

		Private privateCategory As Category
		Public Overridable Property Category() As Category
			Get
				Return privateCategory
			End Get
			Set(ByVal value As Category)
				privateCategory = value
			End Set
		End Property
		Private privateOrder_Details As ICollection(Of Order_Detail)
		Public Overridable Property Order_Details() As ICollection(Of Order_Detail)
			Get
				Return privateOrder_Details
			End Get
			Set(ByVal value As ICollection(Of Order_Detail))
				privateOrder_Details = value
			End Set
		End Property
		Private privateSupplier As Supplier
		Public Overridable Property Supplier() As Supplier
			Get
				Return privateSupplier
			End Get
			Set(ByVal value As Supplier)
				privateSupplier = value
			End Set
		End Property
	End Class
End Namespace
