'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
	Imports System.Collections.Generic
Namespace WCF

	Partial Public Class Region
		Public Sub New()
			Me.Territories = New HashSet(Of Territory)()
		End Sub

		Private privateRegionID As Integer
		Public Property RegionID() As Integer
			Get
				Return privateRegionID
			End Get
			Set(ByVal value As Integer)
				privateRegionID = value
			End Set
		End Property
		Private privateRegionDescription As String
		Public Property RegionDescription() As String
			Get
				Return privateRegionDescription
			End Get
			Set(ByVal value As String)
				privateRegionDescription = value
			End Set
		End Property

		Private privateTerritories As ICollection(Of Territory)
		Public Overridable Property Territories() As ICollection(Of Territory)
			Get
				Return privateTerritories
			End Get
			Set(ByVal value As ICollection(Of Territory))
				privateTerritories = value
			End Set
		End Property
	End Class
End Namespace
