'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
	Imports System.Collections.Generic
Namespace WCF

	Partial Public Class Shipper
		Public Sub New()
			Me.Orders = New HashSet(Of Order)()
		End Sub

		Private privateShipperID As Integer
		Public Property ShipperID() As Integer
			Get
				Return privateShipperID
			End Get
			Set(ByVal value As Integer)
				privateShipperID = value
			End Set
		End Property
		Private privateCompanyName As String
		Public Property CompanyName() As String
			Get
				Return privateCompanyName
			End Get
			Set(ByVal value As String)
				privateCompanyName = value
			End Set
		End Property
		Private privatePhone As String
		Public Property Phone() As String
			Get
				Return privatePhone
			End Get
			Set(ByVal value As String)
				privatePhone = value
			End Set
		End Property

		Private privateOrders As ICollection(Of Order)
		Public Overridable Property Orders() As ICollection(Of Order)
			Get
				Return privateOrders
			End Get
			Set(ByVal value As ICollection(Of Order))
				privateOrders = value
			End Set
		End Property
	End Class
End Namespace
