'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
	Imports System.Collections.Generic
Namespace WCF

	Partial Public Class Supplier
		Public Sub New()
			Me.Products = New HashSet(Of Product)()
		End Sub

		Private privateSupplierID As Integer
		Public Property SupplierID() As Integer
			Get
				Return privateSupplierID
			End Get
			Set(ByVal value As Integer)
				privateSupplierID = value
			End Set
		End Property
		Private privateCompanyName As String
		Public Property CompanyName() As String
			Get
				Return privateCompanyName
			End Get
			Set(ByVal value As String)
				privateCompanyName = value
			End Set
		End Property
		Private privateContactName As String
		Public Property ContactName() As String
			Get
				Return privateContactName
			End Get
			Set(ByVal value As String)
				privateContactName = value
			End Set
		End Property
		Private privateContactTitle As String
		Public Property ContactTitle() As String
			Get
				Return privateContactTitle
			End Get
			Set(ByVal value As String)
				privateContactTitle = value
			End Set
		End Property
		Private privateAddress As String
		Public Property Address() As String
			Get
				Return privateAddress
			End Get
			Set(ByVal value As String)
				privateAddress = value
			End Set
		End Property
		Private privateCity As String
		Public Property City() As String
			Get
				Return privateCity
			End Get
			Set(ByVal value As String)
				privateCity = value
			End Set
		End Property
		Private privateRegion As String
		Public Property Region() As String
			Get
				Return privateRegion
			End Get
			Set(ByVal value As String)
				privateRegion = value
			End Set
		End Property
		Private privatePostalCode As String
		Public Property PostalCode() As String
			Get
				Return privatePostalCode
			End Get
			Set(ByVal value As String)
				privatePostalCode = value
			End Set
		End Property
		Private privateCountry As String
		Public Property Country() As String
			Get
				Return privateCountry
			End Get
			Set(ByVal value As String)
				privateCountry = value
			End Set
		End Property
		Private privatePhone As String
		Public Property Phone() As String
			Get
				Return privatePhone
			End Get
			Set(ByVal value As String)
				privatePhone = value
			End Set
		End Property
		Private privateFax As String
		Public Property Fax() As String
			Get
				Return privateFax
			End Get
			Set(ByVal value As String)
				privateFax = value
			End Set
		End Property
		Private privateHomePage As String
		Public Property HomePage() As String
			Get
				Return privateHomePage
			End Get
			Set(ByVal value As String)
				privateHomePage = value
			End Set
		End Property

		Private privateProducts As ICollection(Of Product)
		Public Overridable Property Products() As ICollection(Of Product)
			Get
				Return privateProducts
			End Get
			Set(ByVal value As ICollection(Of Product))
				privateProducts = value
			End Set
		End Property
	End Class
End Namespace
