'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
	Imports System.Collections.Generic
Namespace WCF

	Partial Public Class Territory
		Public Sub New()
			Me.Employees = New HashSet(Of Employee)()
		End Sub

		Private privateTerritoryID As String
		Public Property TerritoryID() As String
			Get
				Return privateTerritoryID
			End Get
			Set(ByVal value As String)
				privateTerritoryID = value
			End Set
		End Property
		Private privateTerritoryDescription As String
		Public Property TerritoryDescription() As String
			Get
				Return privateTerritoryDescription
			End Get
			Set(ByVal value As String)
				privateTerritoryDescription = value
			End Set
		End Property
		Private privateRegionID As Integer
		Public Property RegionID() As Integer
			Get
				Return privateRegionID
			End Get
			Set(ByVal value As Integer)
				privateRegionID = value
			End Set
		End Property

		Private privateRegion As Region
		Public Overridable Property Region() As Region
			Get
				Return privateRegion
			End Get
			Set(ByVal value As Region)
				privateRegion = value
			End Set
		End Property
		Private privateEmployees As ICollection(Of Employee)
		Public Overridable Property Employees() As ICollection(Of Employee)
			Get
				Return privateEmployees
			End Get
			Set(ByVal value As ICollection(Of Employee))
				privateEmployees = value
			End Set
		End Property
	End Class
End Namespace
